package test

import "encoding/json"

// Code generated by gomacro/generator/gounions. DO NOT EDIT

// UnionWrapper may be used as replacements for Union
// when working with JSON
type UnionWrapper struct {
	Data Union
}

func (out *UnionWrapper) UnmarshalJSON(src []byte) error {
	var wr struct {
		Kind string
		Data json.RawMessage
	}
	err := json.Unmarshal(src, &wr)
	if err != nil {
		return err
	}
	switch wr.Kind {
	case "S":
		var data S
		err = json.Unmarshal(wr.Data, &data)
		out.Data = data

	default:
		panic("exhaustive switch")
	}
	return err
}

func (item UnionWrapper) MarshalJSON() ([]byte, error) {
	type wrapper struct {
		Data interface{}
		Kind string
	}
	var wr wrapper
	switch data := item.Data.(type) {
	case S:
		wr = wrapper{Kind: "S", Data: data}

	default:
		panic("exhaustive switch")
	}
	return json.Marshal(wr)
}

const (
	SUnKind = "S"
)
