// Code generated by gomacro/generator/dart. DO NOT EDIT

String stringFromJson(dynamic json) => json == null ? "" : json as String;

String stringToJson(String item) => item;

typedef JSON = Map<String, dynamic>; // alias to shorten JSON convertors
int intFromJson(dynamic json) => json as int;

int intToJson(int item) => item;
